onlyBuiltDependencies:
    - "@prisma/client"
    - "@prisma/engines"
    - prisma
    - sharp
    - supabase
    - unrs-resolver
minimumReleaseAge: 1440 # 1 day
trustPolicy: no-downgrade
trustPolicyExclude:
    - "semver@6.3.1"
