// Generated by ChatGPT 4o
export function base64ToFile(base64: string, filename: string): File {
    // Split the base64 string to get the data and the MIME type
    const arr = base64.split(",")
    const mime = arr[0].match(/:(.*?);/)![1]
    const bstr = atob(arr[1])
    let n = bstr.length
    const u8arr = new Uint8Array(n)

    while (n--) {
        u8arr[n] = bstr.charCodeAt(n)
    }

    return new File([u8arr], filename, { type: mime })
}

// Generated by ChatGPT 4.0
export async function compressImage(
    file: File,
    maxWidth: number,
    maxHeight: number,
    quality = 0.7, // Compression agressive pour réduire le poids
    outputFormat: "image/webp" | "image/jpeg" = "image/webp" // WebP par défaut, plus léger
): Promise<Blob> {
    return new Promise((resolve, reject) => {
        const img = new Image()
        const reader = new FileReader()

        reader.onload = (event) => {
            if (!event.target?.result) {
                return reject(
                    new Error("Erreur lors du chargement de l'image.")
                )
            }
            img.src = event.target.result as string
        }

        img.onload = () => {
            let { width, height } = img

            // Redimensionnement proportionnel
            if (width > maxWidth || height > maxHeight) {
                const aspectRatio = width / height
                if (width > height) {
                    width = maxWidth
                    height = Math.round(maxWidth / aspectRatio)
                } else {
                    height = maxHeight
                    width = Math.round(maxHeight * aspectRatio)
                }
            }

            const canvas = document.createElement("canvas")
            canvas.width = width
            canvas.height = height
            const ctx = canvas.getContext("2d")

            if (!ctx)
                return reject(
                    new Error("Impossible d'obtenir le contexte du canvas.")
                )

            ctx.drawImage(img, 0, 0, width, height)

            canvas.toBlob(
                (blob) => {
                    if (!blob)
                        return reject(
                            new Error("Erreur lors de la compression.")
                        )
                    resolve(blob)
                },
                outputFormat,
                quality
            )
        }

        reader.onerror = () =>
            reject(new Error("Erreur de lecture du fichier."))
        reader.readAsDataURL(file)
    })
}
