import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <main className="min-h-screen flex flex-col items-center">
          <Header/>
          <div className="flex flex-col flex-1 items-center p-10 w-full">
            {children}
          </div>
          <Footer/>
        </main>
      </body>
      
    </html>
  );
}
